"""Command-line interface for the knowledge-asset audit demo."""

from __future__ import annotations

import argparse
from pathlib import Path

from .core import audit_directory, write_audit_outputs
from .generator import generate_synthetic_dataset


SYNTHETIC_PROVENANCE = (
    "Synthetic demonstration data generated by this repository. No company data, "
    "company code, customer information, or confidential material is included."
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m knowledge_audit",
        description="Inventory, hash, classify, and report on a directory of files.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    generate = subparsers.add_parser(
        "generate", help="Create the deterministic synthetic demonstration corpus."
    )
    generate.add_argument("target", type=Path)
    generate.add_argument(
        "--overwrite",
        action="store_true",
        help="Replace known generated files; unrelated files are never deleted.",
    )

    audit = subparsers.add_parser(
        "audit", help="Audit an input directory and write CSV, JSON, and Markdown outputs."
    )
    audit.add_argument("input", type=Path)
    audit.add_argument("output", type=Path)
    audit.add_argument("--title", default="Knowledge-Asset Audit")
    audit.add_argument(
        "--provenance",
        default="Provenance was not supplied; confirm data handling before sharing.",
    )
    audit.add_argument(
        "--synthetic",
        action="store_true",
        help="Use the repository's explicit synthetic-data provenance statement.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.command == "generate":
        written = generate_synthetic_dataset(args.target, overwrite=args.overwrite)
        print(f"Generated {len(written)} synthetic files in {args.target.resolve()}")
        return 0

    if args.command == "audit":
        provenance = SYNTHETIC_PROVENANCE if args.synthetic else args.provenance
        result = audit_directory(args.input)
        outputs = write_audit_outputs(
            result,
            args.output,
            title=args.title,
            provenance=provenance,
        )
        print(
            "Audited {files} files; found {groups} exact-duplicate group(s) and "
            "{copies} redundant copy/copies.".format(
                files=result.summary["files_discovered"],
                groups=result.summary["exact_duplicate_groups"],
                copies=result.summary["redundant_exact_copies"],
            )
        )
        for name, path in outputs.items():
            print(f"{name}: {path.resolve()}")
        return 0

    raise AssertionError(f"Unhandled command: {args.command}")

